name: My First Workflow
on: [push]
jobs:
  Print-metadata:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was triggered by ${{ github.event_name }}"
      - run: echo "Branch name ${{ github.ref }}"
      - run: echo "Repo name ${{ github.repository }}"
  Check-out-code:
    runs-on: ubuntu-latest
    steps:
      - name: list all files before checking out
        run: |
          ls ${{ github.workspace }}
      - name: check out code
        uses: actions/checkout@v2
      - name: list all files checked out
        run: |
          ls ${{ github.workspace }}
  